---
title: ""
format:
  html:
    page-layout: full
execute:
  message: false
  warning: false
  echo: false
params:
  league: "mens"
---

```{r utils}
source("utils.R")
```

```{r styles}
#| results: asis
paste0(c("<style>", readr::read_lines("styles.css"), "</style>")) |>
  stringr::str_c(collapse = "\n") |>
  cat()
```

# `r sub("s", "'s", stringr::str_to_title(params$league))` March Madness Predictions {.centered}

<p class="smalltext">Chances of each team advancing through the tournament, updated every game-day</p>

```{r dropdown}
#| results: asis

# container for the dropdown
intro <- "<select id='tourneyState' class='cbx' tabindex='50' name='role'>"
outro <- "</select>"

# get set of reference files for the specified league
files <- list.files("~/Desktop/Personal/repos/2025-march-madness/site/plot/")
files <- files[substr(files, 1, nchar(params$league)) == params$league]

# extract set of days from files
days <- sub(paste0(params$league, "-"), "", files)
days <- unique(sub(".html", "", days))
days <- lubridate::ymd(days)
days <- sort(days, decreasing = TRUE)

# set option values
values <- paste("option", 1:length(days), sep = "-")

# set display text
numbers <- scales::label_date("%d")(days)
numbers <- scales::label_ordinal()(readr::parse_number(numbers))
display <- paste(scales::label_date("%B")(days), numbers)

# create option elements
options <- as.character(glue::glue("<option value='{values}'>{display}</option>"))

# coalesce into a dropdown
c(intro, options, outro) |>
  stringr::str_c(collapse = "\n") |>
  cat()
```

```{r main}
#| results: asis
for (day in 1:length(days)) {
  render_child(
    option = values[day],
    league = params$league,
    date = days[day]
  )
}
```


```{r js}
#| results: asis

# convert values to javascript ids
ids <- paste0("\"", values, "\"")
ids <- stringr::str_c(ids, collapse = ", ")
ids <- paste0("var ids=[", ids, "];")

c("<script>", ids, readr::read_lines("options.js"), "</script>") |>
  stringr::str_c(collapse = "\n") |>
  cat()
```

