---
title: ""
format:
  html:
    page-layout: full
execute:
  message: false
  warning: false
  echo: false
params:
  league: "mens"
---

```{r}

```

<style>
@import url('https://fonts.googleapis.com/css2?family=Doto:wght@100..900&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Micro+5&display=swap');

.timer {
  text-align: center;
  font-size: 60px;
  font-weight: 800;
  font-family: "Doto";
  margin-top: 0px;
  color: #838cf1;
}

.dots {
  font-family: "IBM Plex Sans";
  font-size: 60px;
  font-weight: 400;
}

</style>
</head>
<body>

<p class="timer", id="demo"></p>
<p style="text-align:center">Check here after the [first four](https://www.ncaa.com/news/basketball-women/article/2025-03-16/2025-march-madness-womens-ncaa-tournament-schedule-dates-times) have played to see predictions!</p>

<script>
// Set the date we're counting down to
var countDownDate = new Date("Mar 21, 2025 12:00:00").getTime();

// Update the count down every 1 second
var x = setInterval(function() {

  // Get today's date and time
  var now = new Date().getTime();
    
  // Find the distance between now and the count down date
  var distance = countDownDate - now;
    
  // Time calculations for days, hours, minutes and seconds
  var hours = Math.floor(distance / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    
  // Output the result in an element with id="demo"
  document.getElementById("demo").innerHTML = String(hours).padStart(2, '0') + 
  "<span class='dots'>:</span>" + String(minutes).padStart(2, '0') + "<span class='dots'>:</span>" + String(seconds).padStart(2, '0');
    
  // If the count down is over, write some text 
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "EXPIRED";
  }
}, 1000);
</script>

