---
output: html_document
widget: "blank"
active: true
weight: 60

title: "2022 House Forecast"
subtitle: ""

design.background:
  image: ""
  image_darken: 0.6
  
---

```{css custom-width, echo=FALSE}
.interactive_width {
  max-width: 760px;
  padding: 0 20px 0 20px;
  margin: 0 auto 0 auto;
}
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  dpi = 500,
  fig.width = 9,
  fig.height = 6
)

# setup
source("https://github.com/markjrieke/2022-midterm-forecasts/raw/main/site-helpers/setup.R")

# helper functions
source("https://github.com/markjrieke/2022-midterm-forecasts/raw/main/site-helpers/formatting.R")

# interactive charts
source("https://github.com/markjrieke/2022-midterm-forecasts/raw/main/site-helpers/interactive_charts.R")

# interactive table
source("https://github.com/markjrieke/2022-midterm-forecasts/raw/main/site-helpers/interactive_table.R")
```

<div class="interactive_width">

```{r date, include=FALSE}
# setup run date
run_date <- read_rds("https://github.com/markjrieke/2022-midterm-forecasts/raw/main/models/outputs/run_date.rds")
last_run <- format_date(run_date)
```

```{r load-data}
# get current toplines 
house_topline <- 
  read_csv("https://github.com/markjrieke/2022-midterm-forecasts/raw/main/models/outputs/house_topline.csv")

house_distribution <- 
  read_csv("https://github.com/markjrieke/2022-midterm-forecasts/raw/main/models/outputs/current_house_distribution.csv")

candidates <-
  read_csv("https://github.com/markjrieke/2022-midterm-forecasts/raw/main/models/outputs/candidate_predictions.csv",
           locale = locale(encoding = "latin1"))
```






```{r headers, echo=FALSE}
house_title_topline <- 
  house_topline %>%
  filter(model_date == max(model_date)) %>%
  pull(p_dem_win)

house_title <- format_title(house_title_topline, "the House")
house_subtitle <- format_subtitle(house_title_topline, "the House elections")
```


```{r histogram, echo=FALSE}
house_axis <- 
  tibble(breaks = seq(150, 350, 20)) %>%
  mutate(color = case_when(breaks > 217.5 ~ rep_red,
                           breaks < 217.5 ~ dem_blu,
                           TRUE ~ purple),
         labels = case_when(breaks >= 217.5 ~ breaks, 
                            breaks < 217.5 ~ 435 - breaks),
         labels = color_text(labels, color))

house_breaks <- house_axis$breaks
house_labels <- house_axis$labels

house_histogram <-
  house_distribution %>%
  prep_histogram(435, house_title, house_subtitle) +
  scale_x_continuous(breaks = house_breaks,
                     labels = house_labels)

girafe(
  ggobj = house_histogram,
  options = list(
    ggiraph::opts_tooltip(use_fill = TRUE),
    ggiraph::opts_sizing(width = 1)
  )
)
```

<br>

```{r trends, echo=FALSE}
house_probability <-
  house_topline %>%
  prep_probability("the House")

house_seats <-
  house_topline %>%
  prep_seats("the House")

house_patch <- 
  (house_probability / house_seats) +
  plot_annotation(title = "**How the House forecast has changed**",
                  subtitle = paste0("See how each party's forecasted seat total and chance of controlling <br>the Senate have changed over time. The forecast is updated daily."))

ggiraph::girafe(
  ggobj = house_patch,
  height_svg = 8,
  options = list(
    ggiraph::opts_tooltip(use_fill = TRUE),
    ggiraph::opts_sizing(width = 1)
  )
)
```

<br>

```{r candidates, echo=FALSE}
candidates %>%
  prep_table("House")
```

</div>



