---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/authors
  label: Authors
  create: all
  match: "**/*"
- type: directory
  path: content/courses
  label: Courses
  create: all
  match: "**/*"
- type: directory
  path: content/home
  label: Home
  create: all
  match: "**/*"
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
- type: directory
  path: content/project
  label: Project
  create: all
  match: "**/*"
- type: directory
  path: content/publication
  label: Publication
  create: all
  match: "**/*"
- type: directory
  path: content/slides
  label: Slides
  create: all
  match: "**/*"
- type: directory
  path: content/talk
  label: Talk
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
