---
title: Recent Works
author: ''
date: '2021-03-15'
slug: []
categories: [archive]
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-10-13T21:27:19-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

One of the history teachers at my highschool was known for his prolific catchphrase, “give me the stuff, not the fluff,” often uttered to students attempting to submit history papers padded with superfluous words and sentences in order to meet a minimum word threshold. While I never took a class with this teacher, the phrase has stuck with me. With that in mind, I’ve reprioritized some of the things I’ve been working on. Here’s what I’ve been up to over the past week:

* **TX COVID Tracker**: Over the weekend, I put together and published my first Shiny application, a county-level [interactive Texas COVID tracker](https://thedatadiary.net/texas-covid-tracker). Using [data from the New York Times](https://github.com/nytimes/covid-19-data), the tracker lets the user view county-level historical data. The goal is to fill in the gaps of the [Times’ Texas tracker](https://www.nytimes.com/interactive/2020/us/texas-coronavirus-cases.html), which shows historical state data and live county data, but doesn’t offer historical county data.  
* **Classes**: I had previously spent evenings working on projects in R and had pushed off some of the statistics classes to focus on these projects. This past week, I’ve scheduled an hour each day for dedicated class time, alternating daily between a Bayesian inference course and a machine learning course. 

#### My plans for the upcoming week:

* **TX COVID Tracker**: While the interactive tracker is functional, it still leaves a lot to be desired. Being the first Shiny app I developed, I ran into a lot of learning curve issues but should be able to make updates more quickly. This upcoming week, I plan on converting to a [bootstrap layout](https://rstudio.github.io/shinythemes/), adding in an interactive state map with [leaflet](https://rstudio.github.io/leaflet/shiny.html), adding in statewide [hospitalization and vaccination information](https://dshs.texas.gov/coronavirus/AdditionalData.aspx), adding a state and county level [log-log plot](https://www.youtube.com/watch?t=10s&v=54XLXg4fYsc), making some formatting changes to help with mobile viewing, and updating themes/appearances. Eventually, I’d like to write a [scheduleR](https://cran.r-project.org/web/packages/taskscheduleR/vignettes/taskscheduleR.html) script to automatically update the data, but that may need to be put off to focus on the laundry list above.
* **Classes**: I’ll still continue with the daily schedule for coursework and may be able to finish the Bayesian inference course this week. 

Between the COVID tracker and classes, I don’t think I’ll have too much time to work on anything else. That being said, I’ve got some projects/articles in the backlog that I’m looking forward to working on:

* **Polarization - top down or bottom up?** It’s no secret that we are living in the [most polarized political landscape since the Civil War](https://voteview.com/articles/party_polarization), but I’m interested in exploring where this polarization originates. Do elected politicians split the public by pushing increasingly divisive policies? Or do voters lead the polarization effort by increasingly self-segregating into isolated camps? 
* **Two Party PVI (Partisan Voter Index)**: The [partisan voter index (PVI)](https://cookpolitical.com/pvi-0) is a measure of a state’s (or county’s) partisan preference relative to the national environment. There’s a story here about how the national environment is progressing - are our country voting preferences converging or diverging? What states are trending towards Democrats? What states are trending towards Republicans?
* **The Gas Price Fallacy**: I’ve seen quite a few [bad faith attempts to blame increasing gas prices on Joe Biden](https://twitter.com/ksorbs/status/1362540095241347073) recently. Additionally, it’s particularly frustrating that I’ve seen a number of my colleagues in the oil & gas industry repeat this nonsense. As a working member of the oil & gas industry, I think I’m qualified and have a duty to explain why the administration change isn’t the cause of the rising gas prices (the TL;DR version is that we’re recovering from a global pandemic & oil oversupply, you can see that gas prices are just returning to pre-COVID Trump administration levels[here](https://www.gasbuddy.com/charts).)
