---
title: RStudio's Call for Documentation
author: ''
date: '2021-10-05'
slug: []
categories: [archive]
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-10-13T22:39:46-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

In my job, I spend a good amount of time working in the platform setup by our survey vendor, [Qualtrics](https://www.qualtrics.com/). There are some pre-formatted reports that we can send on a recurring basis through Qualtrics, but for one-off or custom reports, I can work with the raw data in R. A few weeks ago, however, I was asked to setup a recurring email to send a customized report to a group of hospital directors each week. While R makes generating the report simple, sending out each week was tedious, as each one needed to be sent separately. Since the reports contain patient information, I couldn't automate via a third party server like [GitHub Actions](https://github.com/features/actions). I needed a way to localize the automation to my computer.

Luckily enough, I was able to work out a solution! I wrote about it in a submission to [RStudio's 2021 Call for Documentation](https://community.rstudio.com/t/r-views-call-for-documentation-announcement/110579). You can read my article on [Automated Email Reports with R, VBA, and the Task Scheduler](https://community.rstudio.com/t/automated-email-reports-with-r-vba-and-the-task-scheduler-r-views-submission/115807/5) for more detail.

### Some programming notes

* I've been named one of RStudio Community's New Users of the Month!
* I've started working in Rmarkdown for these posts (you can actually view the native file for this post here). This allows me to mix in code and prose in one document & should make the process a bit easier on my end.
* I've scheduled out posts every two weeks for the rest of the year. I wanted to give myself enough time to work on some longer term projects, so be on the lookout for more in store!
